import { test, expect } from '@playwright/test';
import { storefrontRequest } from '../helpers/storefront-request.mjs';
const prototype = '/products/lemoon-dalton-prototipo';
const next = (page) => page.locator('[data-configurator-next]').click();
test.beforeEach(async ({ page }) => { expect((await storefrontRequest(page).post('/cart/clear.js')).ok()).toBeTruthy(); });
test.afterEach(async ({ page }) => { await storefrontRequest(page).post('/cart/clear.js'); });

async function startMono(page) {
  await page.goto(`${prototype}?view=configurador`);
  await expect(page.locator('#MainContent h1')).toHaveCount(1);
  const bounds = await page.locator('.lemoon-lens-flow').boundingBox();
  const heading = await page.locator('#MainContent h1').boundingBox();
  expect(heading.x - bounds.x).toBeGreaterThanOrEqual(15);
  await page.getByRole('radio', { name: 'Monofocal', exact: true }).check();
  await page.getByRole('radio', { name: 'Para ver de lejos', exact: true }).check();
  await next(page);
}
async function fillSyntheticRecipe(page) {
  await page.locator('[data-rx="od_sph"]').fill('-1.25');
  await page.locator('[data-rx="oi_sph"]').fill('0');
  await page.locator('[data-rx="pd"]').fill('62');
  await next(page);
}
test('PDP opens the refined flow without adding and preserves the selected frame variant', async ({ page }) => {
  await page.goto(prototype);
  const id = await page.locator('form[data-purchase] [name="id"]').inputValue();
  await page.locator('[data-configure]:visible').click();
  await expect(page).toHaveURL(/view=configurador/);
  expect(new URL(page.url()).searchParams.get('variant')).toBe(id);
  await expect(page.locator('[data-step="use"]')).toBeVisible();
  const cart = await (await storefrontRequest(page).get('/cart.js')).json();
  expect(cart.item_count).toBe(0);
});
test('a direct lens-variant link opens the refined configurator and preserves the native selection', async ({ page }) => {
  const product = await (await storefrontRequest(page).get(`${prototype}.js`)).json();
  const variant = product.variants.find(item => item.available && item.options[1] !== 'Solo armazón');
  expect(variant).toBeTruthy();
  await page.goto(`${prototype}?variant=${variant.id}`);
  await expect(page).toHaveURL(/view=configurador/);
  expect(new URL(page.url()).searchParams.get('variant')).toBe(String(variant.id));
  const data = JSON.parse(await page.locator('[data-lens-data]').textContent());
  expect(String(data.selectedId)).toBe(String(variant.id));
  await page.locator('.lemoon-lens-flow__preview').getByRole('link',{name:'Volver al armazón',exact:true}).click();
  await expect(page.locator('lemoon-eyewear')).toBeVisible();
  expect(new URL(page.url()).searchParams.has('view')).toBe(false);
  expect(new URL(page.url()).searchParams.get('variant')).toBe(String(variant.id));
  await expect(page.locator('[data-configure]')).toBeVisible();
  await expect(page.locator('[data-prescription]')).toBeHidden();
  await page.locator('[data-configure]').click();
  await expect(page).toHaveURL(/view=configurador/);
  expect(new URL(page.url()).searchParams.has('lens_flow')).toBe(false);
  const cart = await (await storefrontRequest(page).get('/cart.js')).json();
  expect(cart.item_count).toBe(0);
});
test('manual configuration adds the exact native variant, price and synthetic recipe to Shopify cart', async ({ page }) => {
  await startMono(page);
  await next(page);
  await expect(page.locator('[data-flow-error]')).toBeVisible();
  await expect(page.locator('[data-rx="od_sph"]')).toBeFocused();
  await fillSyntheticRecipe(page);
  await page.getByRole('radio', { name: 'Transparentes', exact: true }).check();
  await next(page);
  await page.getByRole('radio', { name: 'Estándar 1.50', exact: true }).check();
  await next(page);
  await page.getByRole('radio', { name: 'Con filtro azul', exact: true }).check();
  await next(page);
  await expect(page.locator('[data-step="review"]')).toBeVisible();
  const selectedId = Number(await page.locator('[data-configurator-form] [name="id"]').inputValue());
  const data = JSON.parse(await page.locator('[data-lens-data]').textContent());
  const variant = data.variants.find(({id}) => id === selectedId);
  expect(variant.options).toContain('Monofocal + filtro azul');
  await expect(page.locator('[data-flow-price]')).toHaveText(variant.priceLabel);
  await next(page);
  await expect(page).toHaveURL(/\/cart$/);
  const cart = await (await storefrontRequest(page).get('/cart.js')).json();
  expect(cart.items).toHaveLength(1);
  expect(cart.items[0].variant_id).toBe(selectedId);
  expect(cart.items[0].original_price).toBe(variant.price);
  expect(cart.items[0].properties['OD Esfera']).toBe('-1.25');
  expect(cart.items[0].properties['OI Esfera']).toBe('0');
  expect(cart.items[0].properties['Distancia pupilar (mm)']).toBe('62');
  expect(cart.items[0].properties['OD Adición']).toBeUndefined();
});
test('solar skips unsupported extras and invalidates prescription before real cart submission', async ({ page }) => {
  await startMono(page); await fillSyntheticRecipe(page);
  await page.locator('[data-configurator-back]').click();
  await page.locator('[data-configurator-back]').click();
  await page.getByRole('radio', { name: 'Sol sin receta', exact: true }).check();
  await next(page);
  await page.getByRole('radio', { name: 'Cristales de sol', exact: true }).check();
  await next(page);
  await expect(page.locator('[data-step="review"]')).toBeVisible();
  expect(await page.locator('[data-rx]').evaluateAll(fields => fields.every(field => field.disabled && field.value === ''))).toBe(true);
  const selectedId = Number(await page.locator('[data-configurator-form] [name="id"]').inputValue());
  await next(page); await expect(page).toHaveURL(/\/cart$/);
  const cart = await (await storefrontRequest(page).get('/cart.js')).json();
  expect(cart.items[0].variant_id).toBe(selectedId);
  expect(cart.items[0].properties['OD Esfera']).toBeUndefined();
  expect(cart.items[0].properties['Receta']).toBeUndefined();
});
test('upload validates the file and attaches only a synthetic PDF to the native cart', async ({ page }) => {
  await startMono(page);
  await page.getByRole('radio', { name: 'Subir receta (PDF o imagen)', exact: true }).check();
  const input = page.locator('[data-recipe-file]');
  await next(page);
  await expect(input).toBeFocused();
  await expect(input).toHaveAttribute('aria-invalid', 'true');
  await input.setInputFiles({ name: 'synthetic-prescription.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n% Synthetic test file. No personal or clinical data.\n%%EOF') });
  await next(page);
  await page.getByRole('radio', { name: 'Transparentes', exact: true }).check();
  await next(page);
  await page.getByRole('radio', { name: 'Estándar 1.50', exact: true }).check();
  await next(page);
  await page.getByRole('radio', { name: 'Sin filtro azul adicional', exact: true }).check();
  await next(page);
  await expect(page.locator('[data-recipe-details]')).toContainText('synthetic-prescription.pdf');
  const selectedId = Number(await page.locator('[data-configurator-form] [name="id"]').inputValue());
  await next(page);
  await expect(page).toHaveURL(/\/cart$/);
  const cart = await (await storefrontRequest(page).get('/cart.js')).json();
  expect(cart.items).toHaveLength(1);
  expect(cart.items[0].variant_id).toBe(selectedId);
  expect(cart.items[0].properties['Archivo de receta']).toMatch(/^https:\/\//);
  expect(cart.items[0].properties['OD Esfera']).toBeUndefined();
  expect(cart.items[0].properties['Distancia pupilar (mm)']).toBeUndefined();
});
test('a product without lens packages offers its real frame only and the page fallback has no fictional product', async ({ page }) => {
  await page.goto('/products/lemoon-colca?view=configurador');
  await expect(page.locator('[data-flow-unavailable]')).toBeVisible();
  await expect(page.locator('[data-flow-panels]')).toBeHidden();
  await expect(page.locator('[data-frame-only-add]')).toBeVisible();
  await page.goto('/pages/contact?view=configurador-de-lentes');
  await expect(page.locator('#MainContent h1')).toHaveCount(1);
  await expect(page.locator('#MainContent a[href="/collections/all"]')).toBeVisible();
  await expect(page.locator('#MainContent')).not.toContainText('Dalton');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
